In [474]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fanalysis.ca import CA
from matplotlib.ticker import PercentFormatter

from scipy.stats import chi2_contingency  
from scipy.stats import chi2

data = pd.read_csv('data.csv')

In [475]:
# On ne garde que les 3 premiers caractères de la colonne tag pour comparer les SN1 et les SN2 indépendamment de la réalisation de stages supplémentaires ou non.
data['tag'] = data['tag'].str[:3]

## Comparaison de la distribution des familles de situation

In [476]:
data_FS = pd.pivot_table(data=data, values="record_id", columns="tag", index="FS", aggfunc="count")
data_FS

tag   SN1  SN2
FS
FS01  140   45
FS02  142   52
FS03   56   21
FS04   81   23
FS05   35   17
FS06   10    8
FS07   21    7
FS08   32   39
FS09   53   26
FS10   22   13
FS11   11   10

In [477]:
chi_squared_result=chi2_contingency(data_FS)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  34.56532542960949
La p-valeur du test est :  0.00014808141465778003
Nombre de degré de liberté :  10

Le quantile de la loi du chi 2 à 10 degré de liberté associé au niveau de confiance 0.05 est 18.307038053275146

Valeurs attendues :
 [[129.11458333  55.88541667]
 [135.39583333  58.60416667]
 [ 53.73958333  23.26041667]
 [ 72.58333333  31.41666667]
 [ 36.29166667  15.70833333]
 [ 12.5625       5.4375    ]
 [ 19.54166667   8.45833333]
 [ 49.55208333  21.44791667]
 [ 55.13541667  23.86458333]
 [ 24.42708333  10.57291667]
 [ 14.65625      6.34375   ]]

In [478]:
col_names = list(data_FS.columns)[0:]
row_names = list(data_FS.index)

X = data_FS[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des familles de situation en SN1 et SN2")
display(df)

Distribution des familles de situation en SN1 et SN2

         SN1     SN2
FS01  0.2322  0.1724
FS02  0.2355  0.1992
FS03  0.0929  0.0805
FS04  0.1343  0.0881
FS05  0.0580  0.0651
FS06  0.0166  0.0307
FS07  0.0348  0.0268
FS08  0.0531  0.1494
FS09  0.0879  0.0996
FS10  0.0365  0.0498
FS11  0.0182  0.0383

**Conclusion** : la distribution des familles de situation est significativement différente entre SN1 et SN2 (en analyse univariée).  
En SN1, les 4 FS les plus représentées sont les FS02, 01, 04 et 03. En SN2, on retrouve d'abord les FS02, 01, 08 et 04.  
D'une façon générale, les familles de situation les 4 premières familles de situation, qu'on observe plus fréquemment dans le RAQ (autre thèse) tout niveau de stage confondus semblent moins proposées en SN2 par rapport au SN1. Peut-être par soucis de valoriser des FS qui manqueraient pour certifier ?

## Comparaison de la distribution des problématiques exemplaires

In [479]:
data_PE = pd.pivot_table(data=data, values="record_id", columns="tag", index="PE", aggfunc="count")
data_PE

tag   SN1  SN2
PE
PE01  144   40
PE02   74   36
PE03   26   13
PE04   58   23
PE05   56   33
PE06   41   25
PE07   35   12
PE08   73   23
PE09   52   23
PE10   44   33

In [480]:
chi_squared_result=chi2_contingency(data_PE)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  18.849432352580475
La p-valeur du test est :  0.026504013898568254
Nombre de degré de liberté :  9

Le quantile de la loi du chi 2 à 9 degré de liberté associé au niveau de confiance 0.05 est 16.918977604620448

Valeurs attendues :
 [[128.41666667  55.58333333]
 [ 76.77083333  33.22916667]
 [ 27.21875     11.78125   ]
 [ 56.53125     24.46875   ]
 [ 62.11458333  26.88541667]
 [ 46.0625      19.9375    ]
 [ 32.80208333  14.19791667]
 [ 67.          29.        ]
 [ 52.34375     22.65625   ]
 [ 53.73958333  23.26041667]]

In [481]:
col_names = list(data_PE.columns)[0:]
row_names = list(data_PE.index)

X = data_PE[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des problématiques exemplaires en SN1 et SN2")
display(df)

Distribution des problématiques exemplaires en SN1 et SN2

         SN1     SN2
PE01  0.2388  0.1533
PE02  0.1227  0.1379
PE03  0.0431  0.0498
PE04  0.0962  0.0881
PE05  0.0929  0.1264
PE06  0.0680  0.0958
PE07  0.0580  0.0460
PE08  0.1211  0.0881
PE09  0.0862  0.0881
PE10  0.0730  0.1264

Différence significative avec des variations surtout notables pour les PE01, 05, 10 et 08.

## Comparaison de la distribution des compétences

In [482]:
data_skill = pd.pivot_table(data=data, values="record_id", columns="tag", index="skill", aggfunc="count")
data_skill

tag    SN1  SN2
skill
C1     120   41
C2      90   26
C3     137   46
C4     169   80
C5      63   45
C6      21   22

In [483]:
chi_squared_result=chi2_contingency(data_skill)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  23.398836905432265
La p-valeur du test est :  0.00028315997471253237
Nombre de degré de liberté :  5

Le quantile de la loi du chi 2 à 5 degré de liberté associé au niveau de confiance 0.05 est 11.070497693516351

Valeurs attendues :
 [[112.3255814   48.6744186 ]
 [ 80.93023256  35.06976744]
 [127.6744186   55.3255814 ]
 [173.72093023  75.27906977]
 [ 75.34883721  32.65116279]
 [ 30.          13.        ]]

In [484]:
col_names = list(data_skill.columns)[0:]
row_names = list(data_skill.index)

X = data_skill[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2

       SN1     SN2
C1  0.2000  0.1577
C2  0.1500  0.1000
C3  0.2283  0.1769
C4  0.2817  0.3077
C5  0.1050  0.1731
C6  0.0350  0.0846

## Comparaison de la distribution des items

In [485]:
data_item = pd.pivot_table(data=data, values="record_id", columns="tag", index="ecn_item", aggfunc="count", fill_value=0)
data_item

tag       SN1  SN2
ecn_item
Item 1    122   39
Item 100    2    0
Item 103    0    3
Item 105    1    1
Item 107    3    0
...       ...  ...
Item 94     1    4
Item 95     3    1
Item 96     3    1
Item 98     1    0
Item 99     3    1

[159 rows x 2 columns]

In [486]:
chi_squared_result=chi2_contingency(data_item)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  211.87324315938955
La p-valeur du test est :  0.0027323275066018036
Nombre de degré de liberté :  158

Le quantile de la loi du chi 2 à 158 degré de liberté associé au niveau de confiance 0.05 est 188.33169207932903

Valeurs attendues :
 [[112.60584795  48.39415205]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  6.99415205   3.00584795]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [ 10.49122807   4.50877193]
 [  4.89590643   2.10409357]
 [ 12.58947368   5.41052632]
 [  2.09824561   0.90175439]
 [  2.09824561   0.90175439]
 [  2.09824561   0.90175439]
 [  4.19649123   1.80350877]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [ 38.46783626  16.53216374]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  6.29473684   2.70526316]
 [  6.29473684   2.70526316]
 [  2.09824561   0.90175439]
 [  7.69356725   3.30643275]
 [  4.89590643   2.10409357]
 [  5.59532164   2.40467836]
 [  5.59532164   2.40467836]
 [  3.49707602   1.50292398]
 [  3.49707602   1.50292398]
 [  1.39883041   0.60116959]
 [  1.39883041   0.60116959]
 [  2.79766082   1.20233918]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]
 [  1.39883041   0.60116959]
 [  6.29473684   2.70526316]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  9.79181287   4.20818713]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]
 [  5.59532164   2.40467836]
 [  4.89590643   2.10409357]
 [ 13.28888889   5.71111111]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  9.79181287   4.20818713]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  6.29473684   2.70526316]
 [ 10.49122807   4.50877193]
 [ 18.88421053   8.11578947]
 [  2.79766082   1.20233918]
 [  2.79766082   1.20233918]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  4.19649123   1.80350877]
 [  1.39883041   0.60116959]
 [ 11.89005848   5.10994152]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  6.29473684   2.70526316]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  3.49707602   1.50292398]
 [  7.69356725   3.30643275]
 [  3.49707602   1.50292398]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [ 13.28888889   5.71111111]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  2.79766082   1.20233918]
 [  4.89590643   2.10409357]
 [  1.39883041   0.60116959]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]
 [  0.6994152    0.3005848 ]
 [  5.59532164   2.40467836]
 [  8.39298246   3.60701754]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]
 [  3.49707602   1.50292398]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  1.39883041   0.60116959]
 [  1.39883041   0.60116959]
 [  2.79766082   1.20233918]
 [  0.6994152    0.3005848 ]
 [ 10.49122807   4.50877193]
 [  2.79766082   1.20233918]
 [  2.09824561   0.90175439]
 [  2.79766082   1.20233918]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [ 10.49122807   4.50877193]
 [  8.39298246   3.60701754]
 [  1.39883041   0.60116959]
 [  3.49707602   1.50292398]
 [  1.39883041   0.60116959]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  3.49707602   1.50292398]
 [  2.79766082   1.20233918]
 [  2.79766082   1.20233918]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]]

**Conclusion** : le Chi2 est significatif mais le tableau de contingence comporte de nombreuses valeurs nulles ou inférieures à 5. Il n'est donc théoriquement pas possible d'interpréter les résultats du Chi2.  
Pour essayer de lever cette limite, les valeurs inférieurs à 5 vont être rangés dans une catégorie "autre".

In [487]:
# Ajout d'une colonne "total" pour calculer les effectifs ligne par ligne
data_item['total'] = data_item['SN1'] + data_item['SN2']
data_item.reset_index(inplace=True)

# Seuil pour regrouper les lignes faibles (ex. : < 5)
seuil = 5

# Création d'un groupe : on garde le nom de l'item ou on remplace par "Autres"
data_item['groupe'] = data_item.apply(
    lambda row: row['ecn_item'] if row['SN1'] >= seuil and row['SN2'] >= seuil else 'Autres',
    axis=1
)

# Regroupement par groupe et somme des effectifs
df_grouped = data_item.groupby('groupe')[['SN1', 'SN2']].sum().reset_index()

print(df_grouped)

# Tableau de contingence
contingency = df_grouped[['SN1', 'SN2']].values

df_prop = df_grouped.set_index('groupe')

# Test du Chi²
chi2, p, dof, expected = chi2_contingency(contingency)

# Affichage des résultats
print(f"Chi² = {chi2:.2f}")
print(f"p-value = {p:.4f}")
print(f"Degrés de liberté = {dof}")
print("\nTableau des fréquences attendues :\n", pd.DataFrame(expected, columns=['SN1', 'SN2'], index=df_grouped['groupe']))

tag    groupe  SN1  SN2
0      Autres  334  149
1      Item 1  122   39
2     Item 13   13    5
3    Item 146   46    9
4     Item 19    7   12
5    Item 204    7    7
6    Item 224   21    6
7    Item 247   10    7
8    Item 290   14    5
9    Item 361    6    6
10    Item 66   10    5
11    Item 74    8    7
Chi² = 26.48
p-value = 0.0055
Degrés de liberté = 11

Tableau des fréquences attendues :
                  SN1         SN2
groupe
Autres    337.817544  145.182456
Item 1    112.605848   48.394152
Item 13    12.589474    5.410526
Item 146   38.467836   16.532164
Item 19    13.288889    5.711111
Item 204    9.791813    4.208187
Item 224   18.884211    8.115789
Item 247   11.890058    5.109942
Item 290   13.288889    5.711111
Item 361    8.392982    3.607018
Item 66    10.491228    4.508772
Item 74    10.491228    4.508772

In [488]:
col_names = list(df_prop.columns)[0:]
row_names = list(df_prop.index)

X = df_prop[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2

             SN1     SN2
Autres    0.5585  0.5798
Item 1    0.2040  0.1518
Item 13   0.0217  0.0195
Item 146  0.0769  0.0350
Item 19   0.0117  0.0467
Item 204  0.0117  0.0272
Item 224  0.0351  0.0233
Item 247  0.0167  0.0272
Item 290  0.0234  0.0195
Item 361  0.0100  0.0233
Item 66   0.0167  0.0195
Item 74   0.0134  0.0272

**Conclusion:** Après création de la catégorie "Autres" le chi2 reste significatif. La distribution des Item entre SN1 et SN2 est donc bien significativement différente. Le tableau ci-dessus décrit les proportions des différents items.

## Comparaison de la distribution des RC

In [489]:
data_RC = pd.pivot_table(data=data, values="record_id", columns="tag", index="RC", aggfunc="count", fill_value=0)
data_RC

tag                           SN1  SN2
RC
?                               0    1
ABCÈS SUPERFICIEL               1    0
ABDOMEN DOULOUREUX              2    0
ACCIDENT VASCULAIRE CÉRÉBRAL    0    1
ACNÉ VULGAIRE                   1    2
...                           ...  ...
ÉPIGASTRALGIE                   1    0
ÉPILEPSIE                       1    0
ÉPISTAXIS                       0    1
ÉRYSIPÈLE                       0    1
ÉRYTHÈME                        1    0

[156 rows x 2 columns]

Devant le nombre de valeurs inférieurs à 5 et même égales à 0, création de la catégorie "Autres" d'emblée :

In [490]:
# Ajout d'une colonne "total" pour calculer les effectifs ligne par ligne
data_RC['total'] = data_RC['SN1'] + data_RC['SN2']
data_RC.reset_index(inplace=True)

# Seuil pour regrouper les lignes faibles (ex. : < 5)
seuil = 5

# Création d'un groupe : on garde le nom de l'item ou on remplace par "Autres"
data_RC['groupe'] = data_RC.apply(
    lambda row: row['RC'] if row['SN1'] >= seuil and row['SN2'] >= seuil else 'Autres',
    axis=1
)

# Regroupement par groupe et somme des effectifs
df_grouped = data_RC.groupby('groupe')[['SN1', 'SN2']].sum().reset_index()

print(df_grouped)

# Tableau de contingence
contingency = df_grouped[['SN1', 'SN2']].values

df_prop = df_grouped.set_index('groupe')

# Test du Chi²
chi2, p, dof, expected = chi2_contingency(contingency)

# Affichage des résultats
print(f"Chi² = {chi2:.2f}")
print(f"p-value = {p:.4f}")
print(f"Degrés de liberté = {dof}")
print("\nTableau des fréquences attendues :\n", pd.DataFrame(expected, columns=['SN1', 'SN2'], index=df_grouped['groupe']))

tag                    groupe  SN1  SN2
0                      Autres  249  108
1           DIABÈTE DE TYPE 2   11    7
2                DYSLIPIDÉMIE   14    5
3     DÉPISTAGE ET PRÉVENTION   50   11
4                  DÉPRESSION   11   13
5                         HTA   22    6
6    PROCÉDURE ADMINISTRATIVE   60   47
7                        TOUX    7    7
8                 VACCINATION   48   12
Chi² = 26.71
p-value = 0.0008
Degrés de liberté = 8

Tableau des fréquences attendues :
                                  SN1         SN2
groupe
Autres                    244.918605  112.081395
DIABÈTE DE TYPE 2          12.348837    5.651163
DYSLIPIDÉMIE               13.034884    5.965116
DÉPISTAGE ET PRÉVENTION    41.848837   19.151163
DÉPRESSION                 16.465116    7.534884
HTA                        19.209302    8.790698
PROCÉDURE ADMINISTRATIVE   73.406977   33.593023
TOUX                        9.604651    4.395349
VACCINATION                41.162791   18.837209

In [491]:
col_names = list(df_prop.columns)[0:]
row_names = list(df_prop.index)

X = df_prop[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2

                             SN1     SN2
Autres                    0.5275  0.5000
DIABÈTE DE TYPE 2         0.0233  0.0324
DYSLIPIDÉMIE              0.0297  0.0231
DÉPISTAGE ET PRÉVENTION   0.1059  0.0509
DÉPRESSION                0.0233  0.0602
HTA                       0.0466  0.0278
PROCÉDURE ADMINISTRATIVE  0.1271  0.2176
TOUX                      0.0148  0.0324
VACCINATION               0.1017  0.0556

## Comparaison des spécialités

In [492]:
data_specialty = pd.pivot_table(data=data, values="record_id", columns="tag", index="specialty", aggfunc="count", fill_value=0)
display(data_specialty)

tag                                    SN1  SN2
specialty
Cardiologie                             55   15
Dermatologie                            25   12
Endocrinologie                          28   10
Ethique/Communication/Relation         124   44
Gastroentérologie                       21    5
Gynécologie                             31   10
Hématologie                              2    2
Infectiologie                           22    6
Médecine Interne - Immuno                2    4
Neurologie                              19    8
Néphrologie                              4    0
ORL                                     20   12
Ophtalmologie                            3    1
Orthopédie                              13    9
Pneumologie                             30   15
Psychiatrie                             39   27
Pédiatrie                               58   18
Rhumatologie                            34    9
Santé publique (Administratif/Social)   54   46
Urologie                                17    6

In [493]:
# Test du Chi²
chi2, p, dof, expected = chi2_contingency(data_specialty)

# Affichage des résultats
print(f"Chi² = {chi2:.2f}")
print(f"p-value = {p:.4f}")
print(f"Degrés de liberté = {dof}")
print("\nTableau des fréquences attendues :\n", pd.DataFrame(expected, columns=['SN1', 'SN2'], index=data_specialty.index))

Chi² = 34.84
p-value = 0.0146
Degrés de liberté = 19

Tableau des fréquences attendues :
                                               SN1        SN2
specialty
Cardiologie                             48.918605  21.081395
Dermatologie                            25.856977  11.143023
Endocrinologie                          26.555814  11.444186
Ethique/Communication/Relation         117.404651  50.595349
Gastroentérologie                       18.169767   7.830233
Gynécologie                             28.652326  12.347674
Hématologie                              2.795349   1.204651
Infectiologie                           19.567442   8.432558
Médecine Interne - Immuno                4.193023   1.806977
Neurologie                              18.868605   8.131395
Néphrologie                              2.795349   1.204651
ORL                                     22.362791   9.637209
Ophtalmologie                            2.795349   1.204651
Orthopédie                              15.374419   6.625581
Pneumologie                             31.447674  13.552326
Psychiatrie                             46.123256  19.876744
Pédiatrie                               53.111628  22.888372
Rhumatologie                            30.050000  12.950000
Santé publique (Administratif/Social)   69.883721  30.116279
Urologie                                16.073256   6.926744

In [494]:
col_names = list(data_specialty.columns)[0:]
row_names = list(data_specialty.index)

X = data_specialty[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2

                                          SN1     SN2
Cardiologie                            0.0915  0.0579
Dermatologie                           0.0416  0.0463
Endocrinologie                         0.0466  0.0386
Ethique/Communication/Relation         0.2063  0.1699
Gastroentérologie                      0.0349  0.0193
Gynécologie                            0.0516  0.0386
Hématologie                            0.0033  0.0077
Infectiologie                          0.0366  0.0232
Médecine Interne - Immuno              0.0033  0.0154
Neurologie                             0.0316  0.0309
Néphrologie                            0.0067  0.0000
ORL                                    0.0333  0.0463
Ophtalmologie                          0.0050  0.0039
Orthopédie                             0.0216  0.0347
Pneumologie                            0.0499  0.0579
Psychiatrie                            0.0649  0.1042
Pédiatrie                              0.0965  0.0695
Rhumatologie                           0.0566  0.0347
Santé publique (Administratif/Social)  0.0899  0.1776
Urologie                               0.0283  0.0232