In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fanalysis.ca import CA
from matplotlib.ticker import PercentFormatter

from scipy.stats import chi2_contingency  
from scipy.stats import chi2

data = pd.read_csv('data.csv')

## Chi2 d'indépendance : famille de situation en fonction du parcours de stage.

In [2]:
data_FS = pd.pivot_table(data=data, values="record_id", columns="order_1", index="FS", aggfunc="count")
display(data_FS)

order_1  SN1 avant Urgences  Urgences avant SN1
FS
FS01                     60                  80
FS02                     62                  80
FS03                     23                  33
FS04                     33                  48
FS05                     18                  17
FS06                      3                   7
FS07                     10                  11
FS08                     14                  18
FS09                     17                  36
FS10                      4                  18
FS11                      6                   5

In [3]:
chi_squared_result=chi2_contingency(data_FS)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  10.399565678296621
La p-valeur du test est :  0.4061644990832872
Nombre de degré de liberté :  10

Le quantile de la loi du chi 2 à 10 degré de liberté associé au niveau de confiance 0.05 est 18.307038053275146

Valeurs attendues :
 [[58.04311774 81.95688226]
 [58.87230514 83.12769486]
 [23.2172471  32.7827529 ]
 [33.58208955 47.41791045]
 [14.51077944 20.48922056]
 [ 4.14593698  5.85406302]
 [ 8.70646766 12.29353234]
 [13.26699834 18.73300166]
 [21.973466   31.026534  ]
 [ 9.12106136 12.87893864]
 [ 4.56053068  6.43946932]]

**Conclusion** : La p-value est très supérieure à 0.05 on ne peut pas rejeter l'hypothèse nulle. Il ne semble pas y avoir de corrélation entre le parcours de stage et les familles de situation abordées.  
A noter que certaines valeurs observées et attendues sont inférieures à 5 donc les conditions de validité du test ne sont théoriquement pas vérifiées.

## Chi2 d'indépendance : problématiques exemplaire en fonction du parcours de stage.

In [4]:
data_PE = pd.pivot_table(data=data, values="record_id", columns="order_1", index="PE", aggfunc="count")
display(data_PE)

order_1  SN1 avant Urgences  Urgences avant SN1
PE
PE01                     54                  90
PE02                     33                  41
PE03                     11                  15
PE04                     26                  32
PE05                     27                  29
PE06                     17                  24
PE07                     15                  20
PE08                     28                  45
PE09                     23                  29
PE10                     16                  28

In [5]:
chi_squared_result=chi2_contingency(data_PE)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  3.5145604089287272
La p-valeur du test est :  0.9403704926548697
Nombre de degré de liberté :  9

Le quantile de la loi du chi 2 à 9 degré de liberté associé au niveau de confiance 0.05 est 16.918977604620448

Valeurs attendues :
 [[59.70149254 84.29850746]
 [30.67993367 43.32006633]
 [10.77943615 15.22056385]
 [24.04643449 33.95356551]
 [23.2172471  32.7827529 ]
 [16.99834163 24.00165837]
 [14.51077944 20.48922056]
 [30.26533997 42.73466003]
 [21.55887231 30.44112769]
 [18.24212272 25.75787728]]

**Conclusion** : La p-value est très supérieure à 0.05 on ne peut pas rejeter l'hypothèse nulle. Il ne semble pas y avoir de corrélation entre le parcours de stage et les problématiques exemplaires abordées.

## Chi2 d'indépendance : résultats de consultation en fonction du parcours de stage.

In [6]:
data_RC = pd.pivot_table(data=data, values="record_id", columns="order_1", index="RC", aggfunc="count")
display(data_RC.head)

<bound method NDFrame.head of order_1                    SN1 avant Urgences  Urgences avant SN1
RC
ABCÈS SUPERFICIEL                         NaN                 1.0
ABDOMEN DOULOUREUX                        1.0                 1.0
ACNÉ VULGAIRE                             NaN                 1.0
ALCOOL (PROBLÈME AVEC L’)                 NaN                 1.0
ALGODYSTROPHIE                            NaN                 1.0
...                                       ...                 ...
ÉPAULE (TÉNOSYNOVITE)                     NaN                 2.0
ÉPIGASTRALGIE                             2.0                 NaN
ÉPIGASTRALGIE                             1.0                 NaN
ÉPILEPSIE                                 1.0                 NaN
ÉRYTHÈME                                  NaN                 1.0

[119 rows x 2 columns]>

**Note** : On observe de nombreuses valeurs nulles et quasiment toute les valeurs sont < 5. Le test du Chi2 ne serait donc pas pertinent dans cette situation.

## Chi2 d'indépendance : item en fonction du parcours de stage.

In [7]:
data_item = pd.pivot_table(data=data, values="record_id", columns="order_1", index="ecn_item", aggfunc="count")
display(data_item.head)

<bound method NDFrame.head of order_1   SN1 avant Urgences  Urgences avant SN1
ecn_item
Item 1                  51.0                71.0
Item 100                 1.0                 1.0
Item 105                 1.0                 NaN
Item 107                 1.0                 2.0
Item 110                 3.0                 3.0
...                      ...                 ...
Item 94                  1.0                 NaN
Item 95                  2.0                 1.0
Item 96                  NaN                 3.0
Item 98                  NaN                 1.0
Item 99                  3.0                 NaN

[135 rows x 2 columns]>

**Note** : On observe de nombreuses valeurs nulles et quasiment toute les valeurs sont < 5. Le test du Chi2 ne serait donc pas pertinent dans cette situation.

## Chi2 d'indépendance : compétences en fonction du parcours de stage.

In [8]:
data_skill = pd.pivot_table(data=data, values="record_id", columns="order_1", index="skill", aggfunc="count")
display(data_skill.head)

<bound method NDFrame.head of order_1  SN1 avant Urgences  Urgences avant SN1
skill
C1                       49                  71
C2                       33                  57
C3                       49                  88
C4                       71                  98
C5                       33                  30
C6                       13                   8>

In [9]:
chi_squared_result=chi2_contingency(data_skill)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  9.439400801445391
La p-valeur du test est :  0.0927701454211284
Nombre de degré de liberté :  5

Le quantile de la loi du chi 2 à 5 degré de liberté associé au niveau de confiance 0.05 est 11.070497693516351

Valeurs attendues :
 [[49.6        70.4       ]
 [37.2        52.8       ]
 [56.62666667 80.37333333]
 [69.85333333 99.14666667]
 [26.04       36.96      ]
 [ 8.68       12.32      ]]

**Conclusion** : La p-value est supérieure à 0.05, on ne peut pas rejeter l'hypothèse nulle. On ne retrouve pas d'association entre le profil de compétences présentées et le parcours de stage.

In [10]:
data_specialty = pd.pivot_table(data=data, values="record_id", columns="order_1", index="specialty", aggfunc="count")
display(data_specialty.head)

<bound method NDFrame.head of order_1                                SN1 avant Urgences  Urgences avant SN1
specialty
Cardiologie                                          22.0                33.0
Dermatologie                                          7.0                18.0
Endocrinologie                                       11.0                17.0
Ethique/Communication/Relation                       52.0                72.0
Gastroentérologie                                     9.0                12.0
Gynécologie                                          14.0                17.0
Hématologie                                           1.0                 1.0
Infectiologie                                         9.0                13.0
Médecine Interne - Immuno                             NaN                 2.0
Neurologie                                            9.0                10.0
Néphrologie                                           2.0                 2.0
ORL                                                   7.0                13.0
Ophtalmologie                                         1.0                 2.0
Orthopédie                                            5.0                 8.0
Pneumologie                                          14.0                16.0
Psychiatrie                                          12.0                27.0
Pédiatrie                                            23.0                35.0
Rhumatologie                                         12.0                22.0
Santé publique (Administratif/Social)                28.0                26.0
Urologie                                             11.0                 6.0>